{% set name = "gepetto-viewer" %}
{% set version = "4.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Gepetto/gepetto-viewer/releases/download/v{{ version }}/gepetto-viewer-{{ version }}.tar.gz
  sha256: 5d112e7e6263dafe934f165bc6bdf23f5c387ee2c0469117c92e5436a495d1d5
  patches:
    - patches/qcontext_fix.patch
    - patches/qt_opengl_option.patch

build:
  number: 4
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - doxygen
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxext') }}               # [linux]
  host:
    - boost-cpp
    - assimp
    - octomap
    - urdfdom
    - ffmpeg
    - qt
    - openscenegraph
    - openscenegraph-osgqt
  run:
    - boost-cpp

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/bin/gepetto-gui

about:
  home: https://github.com/Gepetto/gepetto-viewer
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Graphical Interface for Pinocchio and HPP
  description: |
    Graphical Interface for Pinocchio and hpp
  doc_url: https://gepettoweb.laas.fr/hpp/gepetto-viewer/doxygen-html/index.html
  dev_url: https://github.com/Gepetto/gepetto-viewer

extra:
  recipe-maintainers:
    - ymontmarin
    - jcarpent
