{% set name = "gepetto-viewer" %}
{% set version = "4.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Gepetto/gepetto-viewer/releases/download/v{{ version }}/gepetto-viewer-{{ version }}.tar.gz
  sha256: 8d2763b63f987338bd2cb67cbc161a1e2efcef9d9be8af49412ccb234cbb8476
  patches:
    - patches/fix_nox11.patch
    - patches/osx_fix_gldebugproc.patch  # [osx]

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - doxygen
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ cdt('mesa-libgl-devel') }}       # [linux]
    - {{ cdt('mesa-dri-drivers') }}       # [linux]
    - {{ cdt('libselinux-devel') }}       # [linux]
    - {{ cdt('libxdamage-devel') }}       # [linux]
    - {{ cdt('libx11-devel') }}           # [linux]
    - {{ cdt('libxfixes') }}              # [linux]
    - {{ cdt('libxxf86vm') }}             # [linux]
    - {{ cdt('libxext') }}                # [linux]
  host:
    - boost-cpp
    - assimp
    - octomap
    - urdfdom
    - ffmpeg
    - qt-main
    - openscenegraph
    - openscenegraph-osgqt
    - python
  run:
    - boost-cpp
    - python

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/bin/gepetto-gui

about:
  home: https://github.com/Gepetto/gepetto-viewer
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Graphical Interface for Pinocchio and HPP
  description: |
    Graphical Interface for Pinocchio and hpp
  doc_url: https://gepettoweb.laas.fr/hpp/gepetto-viewer/doxygen-html/index.html
  dev_url: https://github.com/Gepetto/gepetto-viewer

extra:
  recipe-maintainers:
    - ymontmarin
    - jcarpent
